FACEBOOK_KEY: "1705344566438795"
FACEBOOK_SECRET: "6ff5eb9d4884d4b8eba87925cd11bdaf"
EDMUNDS_API_KEY: "jdq9c2drnq3nqqwpcek7ynjv"
VAPID_PUBLIC_KEY: "BEUG4gsOxr0PpslKtmxJFtdYcP4OsiVJvqwTnu0-Vssw1RBV26LtU5Urmq-GKYxwW-yc2veE79xe4aIcidVsV1Q="
VAPID_PRIVATE_KEY: "jV8sSqvccQiwvE_alD933swbDvXdvXLHFgWu-PE4BmU="